# Site
repository: mikonoid/mikonoid.gihub.io

# Personal info
name: Mike Ivanov
title: Devops Engineer
email: mikonoid@gmail.com
website: http://itkitchen.net

# Social links
github_username:  mikonoid
facebook_username: mikenoid
instagram_username: slon.gobo
linkedin_username: mikhail-ivanov-bb585160

# About Section
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
 I'm senior Devops Engineer. 
 I have worked at a number of companies gaining teamwork and a lot of skills. 
 As well I have experience with private clouds and building big projects from scrath. 
 I am most skilled in: 
 * <mark>Ansible</mark>
 * <mark>Openstack</mark>,
 * <mark>k8s</mark>
 * <mark>High Availability</mark>
 * <mark>Clustering</mark> 

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
  * Triathlon
  * Cycling
  * Hiking

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
